// Generated by CoffeeScript 1.10.0

/* app.coffee */

(function() {
  var app, express, path, server;

  path = require('path');

  express = require('express');

  app = express();

  app.use(express["static"](path.join(__dirname, 'public')));

  app.set('view engine', 'jade');

  app.use('/', require('./routes'));

  app.set('port', process.env.PORT || 5000);

  server = app.listen(app.get('port'), function() {
    var host, port;
    host = server.address().address;
    port = app.get('port');
    return console.log("Application server running at http://" + host + ":" + port);
  });

}).call(this);
